Repository Vita-App/Vita, pull requests merged in 2022-04, with the labels that each got.

#47 Added Google Oauth
  api/package-lock.json
  api/package.json
  api/src/Models/User.ts
  api/src/config/connectDatabase.ts
  api/src/config/keys.ts
  api/src/config/passport-config.ts
  api/src/controllers/auth-controller.ts
  api/src/index.ts
  api/src/routes/apiRoutes.ts
  client/src/components/AuthForm/index.tsx
  client/src/setupProxy.ts
Labels: GSSoC22, Level3

#69 Adding Authentication with JWTs
  api/package-lock.json
  api/package.json
  api/src/Models/User.ts
  api/src/config/keys.ts
  api/src/controllers/auth-controller.ts
  api/src/index.ts
  api/src/middleware/index.ts
  api/src/middleware/jwtAuth.ts
  api/src/routes/apiRoutes.ts
  api/src/types.d.ts
Labels: GSSoC22, Level3

#84 [Homepage]: Get Mentorship from Alumni - Fix
  client/src/components/Carousel/Carousel.styles.ts
  client/src/components/Carousel/CarouselToolbar.tsx
  client/src/components/Carousel/index.tsx
Labels: GSSoC22, Level2

#102 Mentor Values Component - Developed
  client/public/Illustration/Diversity.svg
  client/public/Illustration/FreeOfCharge.svg
  client/public/Illustration/VettedVerified.svg
  client/src/components/MentorValues/MentorValues.styles.ts
  client/src/components/MentorValues/ValueCard.style.ts
  client/src/components/MentorValues/ValueCard.tsx
  client/src/components/MentorValues/index.tsx
  client/src/components/MentorValues/mentorValuesData.ts
  client/src/pages/Landing/index.tsx
Labels: frontend 🎨, GSSoC22, Level2
