Repository Vita-App/Vita, pull requests merged in 2022-03, with the labels that each got.

#34 Fixed Typos in Card Description
  client/src/data/topics.ts
Labels: GSSoC'22, Level-1

#35 Fix typo error - issue #30
  client/src/components/DaterPicker/ConfirmationPage.tsx
Labels: GSSoC'22, Level-1

#49 #issue46: Added Limit Query Param
  api/src/controllers/api-controller.ts
Labels: GSSoC'22, Level-2

#44 Add: meta data description and structured markup
  client/public/index.html
Labels: GSSoC'22, Level-1

#40 fts on mentor implemented
  .github/ISSUE_TEMPLATE/New Issue.yaml
  README.md
  api/src/Models/User.ts
  api/src/config/connectDatabase.ts
  api/src/controllers/api-controller.ts
  api/src/routes/apiRoutes.ts
  client/src/components/UserDashboard/Drawer.tsx
  client/src/components/UserDashboard/Toolbar.tsx
  client/src/pages/Dashboard/Booking.tsx
  client/src/pages/Dashboard/index.tsx
  client/src/pages/routes.tsx
  client/src/utils/settings.ts
Labels: GSSoC22, Level2

#59 Adding Auth Route
  client/package-lock.json
  client/package.json
  client/src/components/Appbar/Toolbar.tsx
  client/src/components/AuthForm/index.tsx
  client/src/index.css
  client/src/pages/Auth/index.tsx
  client/src/pages/routes.tsx
  client/src/utils/hooks/theme.ts
Labels: GSSoC22, Level3

#64 Adding Complete Signup Route
  client/package-lock.json
  client/package.json
  client/public/i1.svg
  client/public/i2.svg
  client/src/components/Auth/Signup/Cards/index.tsx
  client/src/components/Auth/Signup/SignUpSteps/ExperienceStep.tsx
  client/src/components/Auth/Signup/SignUpSteps/IntegrationsStep.tsx
  client/src/components/Auth/Signup/SignUpSteps/ProfileStep.tsx
  client/src/components/Auth/Signup/SignUpSteps/index.tsx
  client/src/components/Auth/Signup/SignUpSteps/utils.tsx
  client/src/components/Auth/Signup/index.tsx
  client/src/components/AuthForm/index.tsx
  client/src/components/common/index.ts
  client/src/data/select.ts
  client/src/pages/Auth/Signup/index.tsx
  client/src/pages/routes.tsx
Labels: GSSoC22, Level3
